# EXTRA_CFLAGS	+= -O0

obj-y	+= data.o syscall.o stacktrace.o syscall_filename.o interpreter.o
obj-y	+= dwarf-cfi.o dwarf-expression.o dwarf-fde.o dwarf-read.o 
ccflags-y := -Isecurity/pfwall/modules/context/include
