#!/usr/bin/env python
import sys
import os
import time

log_file="/var/log/pfw.log"
in_file="/sys/kernel/debug/wall_interfaces0"
pid_file="/sys/kernel/debug/pft_log_daemon_pid"
enabled_file="/sys/kernel/debug/pfwall_enabled"

enf = open(enabled_file, "w")
enf.write("1")
enf.close()

pidf = open(pid_file, "w")
pidf.write(str(os.getpid()))
pidf.close()

inf = open(in_file, "r")
outf = open(log_file, "a+")

while True:
	time.sleep(1)
	s = inf.read()
	outf.write(s)

outf.write("EXITING")
